#test
#FROM ubuntu:20.04
FROM scratch
MAINTAINER wjg
#RUN /bin/bash echo 134 
ADD a.out /
ADD ttt /wjg/
#RUN /a.out
#RUN yun update
#CMD ["/ttt"]
#RUN ["/ttt"]
#CMD ["/a.out"]
CMD ["/wjg/ttt"]
#RUN ["/ttt"]
#CMD ["/a.out“]
#RUN ./a.out
