##############################



######abc bbb ccc ddd eee fff ggg 
######hhh iii ggg kkk llll jjj mmm
######111 222
######112 222
######113 222
######114 222
######115 222
######116 222
va=123
override vb=111

.PHONY : all

all:
	@echo $(va)
	@echo $(vb)
